# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
mod_id=headlines
mod_name=Headlines
maven_group = com.clemensu42
archives_name = headlines
enabled_platforms = fabric,neoforge
mod_license=MIT
mod_release_type=alpha
mod_authors=ClemensU42
mod_description=Exposure-Addon for writing and distributing newspapers
mod_page=https://modrinth.com/project/headlines
mod_modrinth_project_id=szVEDv8S
mod_github=https://github.com/ClemensU42/Headlines
mod_issues=https://github.com/ClemensU42/Headlines/issues

# Minecraft properties
minecraft_version = 1.21.1
parchment_version=1.21:2024.07.28
minecraft_version_range=[1.21,)
supported_minecraft_versions=1.21,1.21.1

# Fabric
fabric_loader_version = 0.19.5
fabric_api_version = 0.116.17+1.21.1

# NeoForge
neoforge_version = 21.1.248
neoforge_version_range=[21,)
neoforge_loader_version_range=[4,)

# Dependencies
architectury_api_version = 13.0.11
yarn_mappings_patch_neoforge_version = 1.21+build.6
exposure_version=1.9.18
required_exposure_version_range_forge=[1.9.0,)
required_exposure_version_range_fabric=>=1.9.0
forge_config_api_port_version=21.1.0
